language: python
python: 3.8

install: 
    - "pip install -r requirements.txt"

script:
    - python3 -m pytest test
    - python3 setup.py sdist --formats=gztar,zip

deploy:
    provider: releases
    skip_cleanup: true
    on:
        tags: true
    file_glob: true
    file:
        - dist/tarot-pkg-ensta-agile-project-$TRAVIS_TAG.tar.gz
        - dist/tarot-pkg-ensta-agile-project-$TRAVIS_TAG.zip
    api_key:
        secure: "e3quukfhfQFdoEZ6PR7w9X/LCNCQ3d/0Xt9CpYOVsEat3xSK9V2tCmtYkWBtbXJIXAHeIkvWYD5qgDFNUY3KNhp2OADygTTA0oioz1rNtRUoQ02Vl4psjAFH9RtN+ygz1NzhWfWMHSmLrHvktlblwoj7QUmmGXkxZTYWmDvifrqQR2gNDJo0F+lYx5S3mD/ogj21BbIOUnnqvShdYyugYES0A/HZQXFIxL0j0Bao8OhKrT678bD6WwcMq4gFd3b/RY4srJVHmOghhUQl1TMEya9UFsGPQYbe1edCz9dpSAr3BHy/jO3JprRAHgCpzSfehMU87wUJry25cuvn8HPIlJdmxCAGHBW48egxD6KsUqtbqzdooMR8ImwBiasrF+1Py0ZG3eZhTmLZY7MjjvwKzmVVUCCzJpbNZY1w3m7xWuDZG93K8n7/7/HqZLkasXiZE+xSdjmyI0rNdykbewgUfibwHAfrKHHS67EKA2RqI06I6FJHRCPLftijiXXiNxKlGsvLnG9VzzsJ+ILWddOjnXd0d3Iz12lm3qt8Y3c7Draa40C/XGXJA2XceuFUxBOhkWbxqBm8c9t3/qqJDk0KxgyXjzxUCP6nHttuw80HCP73tNMfo6VIbOXFITHNfUhOC7lO3OgacS6mG8fTLaqA06IS+K8bHQ2C/E64GOWnX74="
