language: python
python: 3.6

install: 
    - "pip install -r requirements.txt"

script:
    - python3 -m pytest test
    - python3 setup.py sdist --formats=gztar,zip

deploy:
    provider: releases
    skip_cleanup: true
    on:
        tags: true
    file_glob: true
    file:
        - dist/tarot-pkg-ensta-agile-project-$TRAVIS_TAG.tar.gz
        - dist/tarot-pkg-ensta-agile-project-$TRAVIS_TAG.zip
    api_key:
        secure: "WXyEj4f8U/7eB60M7ZY40+GkqzfQ9JdkRAr5ii+W57f2Cgh7oZDiF6Y0Pka17hWQhkEXHlQtfCA1rq/dthVLKGl0Wj58+poUVrm4qVteEA0QaQlt0JfDXV99/TIj2XO5zIuivt483FkffTuhVGIHPin8XgCM4ME46Wzn1entzpAztJPNfHOQPMYcMxj2+qZLMSjzygrAu7AQ2KdM96tIgaIVgjjr8Oa7dBD3hNvjwZ03nYOmqSI9XHf49a54crrAh0MeYtox0X6vw6myPr4dPYEkgXhZa6jkom83S1CUNeQRDLxNGEf051dTA8eF7KYk3xGU+QQON2GA1BSDqD8qLJQkv05/NGdbtgOLpfvkZGHEWlo6HYI6LeKsXJo4rjJK1UujweFq1/HZbz7Deg5E9paT2XCVR3i+Nv38vcGxeVPs02pEefvm99CDAmdm0W5VwGghtt6omt8MjepiT2813FJNiDYUJrk2vVndlak4OtDy1nMgI8/79ReSww9wpqtWHz66jMaKUpsvxpA5op7UOKHrzm0YBFtlQdocRKTJUrrMzKHUnOybfjgk2UyE06bJTXxq9GiGLBSGNKU6077Pg/xJLIm6aku4h2x5QqbuNQcgIY47sRF2sfvu4jo7ABSK/NUnOpkrAMF8c1HWdqT/nFUysYOdEvGNGnuAQMIsUj8="
